services:
  backend:
    container_name: digicon_trap1_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./server:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: mysql
      DB_PORT: 3306
      DB_DATABASE: digicon_trap1
      AWS_LAMBDA_URL: https://bnixaqzsrcyhxgiuywfoynpf4y0jhcby.lambda-url.us-east-1.on.aws/
      AWS_S3_BUCKET_NAME: digicon-trap1-public
      AWS_REGION: us-east-1
    ports:
      - "8080:8080"
  mysql:
    container_name: digicon_trap1_mysql
    image: mariadb:10.7.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: digicon_trap1
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/sql
    healthcheck:
      test: mysql --user=root --password=password --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 60
